/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'MarkPerry' at '29/03/14 5:49 AM' with Gradle 1.11
 *
 * @author MarkPerry, @date 29/03/14 5:49 AM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
