/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'MarkPerry' at '29/03/14 5:49 AM' with Gradle 1.11
 *
 * @author MarkPerry, @date 29/03/14 5:49 AM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
